### ISSUE TITLE
How does mini-ndn virutalize nodes?

### ISSUE THREAD

**Issue by azzamsu** [named-data/mini-ndn#2]
Hello,
I've been using mini-ndn for a couple of days, and it's awesome. I guess my question is: how does mini-ndn virtualize nodes? Do nodes share memory and storage? Because whenever I try to modify the NFD configuration on one node, I discover that the changes are reflected in all other nodes.

Thanks,
Azzam

**Comment by agawande** [comment]
Glad you like it!
Okay so when you modify the nfd.conf (say in /tmp/a/nfd.conf) and then run minindn again it installs the file again from /usr/local/etc/mini-ndn/nfd.conf.

Go to https://github.com/named-data/mini-ndn/blob/master/ndn/nfd.py
Delete line https://github.com/named-data/mini-ndn/blob/master/ndn/nfd.py#L43

(You might want to delete line 46 and 49 too as those are the lines which modify nfd.conf for log level and sock file)

Then reinstall mini-ndn. Now you can modify the other files in /tmp and safely run minindn again.

(Or instead of doing this, you may modify the file at /usr/local/etc/mini-ndn/nfd.conf, but keep in mind this will make all the nodes have the same config file).

**Comment by azzamsu** [comment]
Thanks for your response,

I did that, and I'm still facing the same problem. For example, when I "register" a face using nfdc in one node, it gets registered in all other nodes. It seems like they are running the same nfd process.
Any idea on how to get around that?

**Comment by agawande** [comment]
Can you please tell me step by step what you did?

**Comment by azzamsu** [comment]
I commented out lines 43, 46, and 49. Then I removed the executable file minindn, and I ran 'sudo install.sh -i'. Prior to launching minindn, I modified the nfd.conf file for each node (in /tmp/nodename).
I discovered that the all nodes connect to the same nfd.sock socket when they are running nfd. I think this is the heart of the problem, and I'm trying to figure out a way around this. Am I on the right path?

**Comment by agawande** [comment]
In your nfd.conf file make sure you have different sock file path for each:
https://github.com/named-data/NFD/blob/master/nfd.conf.sample.in#L86 
(ex: for node a it could be /var/run/a.conf and so on).

Also there should be a /tmp/a/.ndn/client.conf file where you might need to modify the sock file path as well.

**Comment by azzamsu** [comment]
It's working! Thanks a lot for the help :)
