### ISSUE TITLE
ndntools error

### ISSUE THREAD

**Issue by whiteysy** [named-data/mini-ndn#21]
There are some errors when i use minindn by ndntools. It does not support the command of  ndnpoke/ndnpeek. It displays "bash: not found this command". And when i build ndntools by waf, it dispalys some error and building fails.

**Comment by whiteysy** [comment]
../tools/peek/ndnpeek/ndnpeek.cpp: In member function ‘ndn::Interest ndn::peek::NdnPeek::createInterest() const’:
../tools/peek/ndnpeek/ndnpeek.cpp:83:14: error: ‘class ndn::Interest’ has no member named ‘setForwardingHint’
     interest.setForwardingHint(m_options.link->getDelegationList());
              ^
../tools/peek/ndnpeek/ndnpeek.cpp:83:48: error: ‘class ndn::Link’ has no member named ‘getDelegationList’
     interest.setForwardingHint(m_options.link->getDelegationList());

**Comment by agawande** [comment]
When Mini-NDN installs ndn-cxx etc. it is using an older version because NLSR is not ready to work with latest ndn-cxx yet. So ndn-tools latest version is not compiling for peek/poke. Can you please try to roll back to an older version and then try to compile. (Try this and see if compilation works in ndn-tools:
git checkout c9575a6aa3372875aecb627d9e169c0955135bd8).

Other option is to update ndn-cxx, NFD to latest version (by git pull in the respective repositories). Then NLSR will not work. We are working on the compiling NLSR with the latest version of ndn-cxx (https://gerrit.named-data.net/#/c/4141/ and using it with Mini-NDN: https://gerrit.named-data.net/#/c/4141/).

**Comment by whiteysy** [comment]
Thanks for your reply！！！Does the latest Mini-NDN  support other ndn-tools like ndnping ndncatchunks dump and so on ? When i use 'xterm a' and use the command of ndn-tools in a small frame of node a,it displays "error: while connecting to the forwarder (connection refused)"

**Comment by whiteysy** [comment]
And the command of ndn-tools can be used in 'mini-ndn>'.

**Comment by whiteysy** [comment]
After i rebuild the NFD successfully by waf , it displays "error: while connecting to the forwarder (No such file or directory ).

**Comment by agawande** [comment]
Yes any tool can be used from the Mini-NDN command line - just run the commands in background (ex: a ndnpingserver /ndn/edu/pingserver &> logs &).
For xterm try: export HOME=/tmp/<node-name> && cd ~

**Comment by whiteysy** [comment]
Appreciate your reply so quickly, but it still display "error:while connecting to the forwarder (No such file or directory)" after i try what you said. Although it does not impact the daily work because the command can be used from the Mini-NDN command line.

**Comment by agawande** [comment]
Oops I mistyped, try this:
export HOME=/tmp/\<node-name\> && cd ~
for example export HOME=/tmp/a/ && cd ~
(You can also use this command outside of Mini-NDN in a separate terminal - not just xterm).

**Comment by whiteysy** [comment]
Thanks you so much! I have solved the problem!
