### ISSUE TITLE
minindnedit Command Not Found

### ISSUE THREAD

**Issue by Rj2014** [named-data/mini-ndn#51]
When typing the following command:
sudo minindnedit
to open the GUI program Mini-NDN Edit, It says: 
sudo: minindnedit: command not found
![Screenshot from 2020-10-11 00-39-10](https://user-images.githubusercontent.com/36701813/95663154-49ea8300-0b5a-11eb-92cb-a40a14caae7e.png)

**Comment by dulalsaurab** [comment]
We have removed the GUI support from Mini-NDN and is no longer available. Please see the release notes [release 0.5.0](http://minindn.memphis.edu/release-notes.html#mini-ndn-version-0-5-0-major-changes-since-version-0-4-0)
and the redmine [Mini-NDN re-design](https://redmine.named-data.net/issues/5062)
