### ISSUE TITLE
How to simulate new cache replacement policy and see the metrics

### ISSUE THREAD

**Issue by Rj2014** [named-data/mini-ndn#53]
My team has developed a new cache replacement policy and we want to simulate it in mini-ndn using the new cache replacement policy instead of the default policy. Does anybody have any idea how to simulate it and find the metrics? We want to use the ndn-grid.cpp scenario for this purpose.

**Comment by agawande** [comment]
To emulate (simulation is ndnSIM, we say emulate because real NFD is running in Mini-NDN) in Mini-NDN simply install NFD to the system (sudo ./waf install)  and set appropriate policy when setting up NFD
 (https://github.com/named-data/mini-ndn/blob/master/minindn/apps/nfd.py#L31) See examples folder too if you haven't already.
